#!/bin/bash

if [ -f "$HOME/.bashrc" ]; then

	echo " export HELLO=$HOSTNAME" >> "$HOME/.bashrc"
	echo " LOCAL=$(whoami)" >> "$HOME/.bashrc"
	
	echo "$HOME/.bashrc"
	
	gnome-terminal
else
	echo ".bashrc not found"
fi
